#index:
#    path: /
#    controller: App\Controller\DefaultController::index

front_office_home:
    path: /
    controller: App\Controller\FrontOfficeController::index
add_to_panier:
    path: /add-to-panier/{ref}
    controller: App\Controller\PanierController::addToPanier
checkout_process:
    path: /checkout
    controller: App\Controller\PanierController::checkoutProcess

success_url:
    path: /success-url
    controller: App\Controller\PanierController::successUrl
    methods: ['GET']

cancel_url:
    path: /cancel-url
    controller: App\Controller\PanierController::cancelUrl
    methods: ['GET']

